/**
 * Delivery tracking — the portfolio of corrective actions that people have proposed, approved and
 * are delivering. Pure types and functions; storage lives in ./store.
 *
 * An action generated by the Planning Lab is only ever a proposal. It enters the portfolio when a
 * person proposes it, becomes "approved" only through an explicit approval decision by someone with
 * the approver role, and its progress is what people record — milestones ticked and KPI readings
 * entered — never anything the models infer.
 */
import type { GovId, L, Severity } from "@/types/census";
import type { ActionItem, ActionSector, Horizon } from "@/simulation/lab/actions";

export type Stage = "PROPOSED" | "APPROVED" | "IN_DELIVERY" | "DONE" | "DROPPED";
export type Role = "VIEWER" | "PLANNER" | "APPROVER";
export type Health = "NOT_STARTED" | "ON_TRACK" | "AT_RISK" | "OFF_TRACK" | "DONE" | "DROPPED";

/** Who did something. In the shared workspace only the opaque platform id is stored (names are
 *  resolved when rendering); in the local workspace the acting-officer label from Settings. */
export interface Actor {
  id: string | null;
  name: string;
}

export interface Milestone {
  id: string;
  title: L;
  due: string; // YYYY-MM-DD
  done: boolean;
  doneAt?: string;
}

export interface KpiReading {
  at: string; // ISO
  value: number;
  by: Actor;
}

export interface PortfolioItem {
  id: string;
  kind: string;
  govId: GovId;
  sector: ActionSector;
  severity: Severity;
  horizon: Horizon;
  title: L;
  rationale: L;
  target: L;
  lead: L;
  costM: number;
  beneficiaries: number;
  href: string;
  /** stage as recorded on the item; "APPROVED" is derived from the approval record */
  stage: Exclude<Stage, "APPROVED">;
  owner: string;
  milestones: Milestone[];
  kpi: { unit: string; baseline: number; target: number; readings: KpiReading[] };
  spentM: number;
  createdAt: string;
  createdBy: Actor;
  updatedAt: string;
  /** created by "Load demo portfolio" — progress values are simulated */
  demo?: boolean;
}

export interface Approval {
  itemId: string;
  decision: "APPROVED" | "RETURNED";
  note: string;
  at: string;
  by: Actor;
}

export interface Comment {
  id: string;
  itemId: string;
  text: string;
  at: string;
  by: Actor;
}

export type EventKind = "PROPOSED" | "APPROVED" | "RETURNED" | "STAGE" | "OWNER" | "MILESTONE" | "MILESTONE_ADDED" | "KPI" | "SPEND" | "COMMENT" | "VERSION" | "REMOVED" | "DEMO";

export interface AuditEvent {
  id: string;
  itemId: string | null;
  kind: EventKind;
  detail: string;
  at: string;
  by: Actor;
}

export interface VersionRow {
  id: string;
  title: L;
  govId: GovId;
  sector: ActionSector;
  stage: Stage;
  health: Health;
  costM: number;
  progress: number;
}

export interface Version {
  id: string;
  name: string;
  at: string;
  by: Actor;
  rows: VersionRow[];
}

export interface DeliveryData {
  items: Record<string, PortfolioItem>;
  approvals: Record<string, Approval>;
  comments: Comment[];
  events: AuditEvent[];
  versions: Version[];
}

export const EMPTY: DeliveryData = { items: {}, approvals: {}, comments: [], events: [], versions: [] };

export const STAGES: Stage[] = ["PROPOSED", "APPROVED", "IN_DELIVERY", "DONE"];

export const STAGE_LABEL: Record<Stage, L> = {
  PROPOSED: { en: "Proposed", ar: "مقترح" },
  APPROVED: { en: "Approved", ar: "معتمد" },
  IN_DELIVERY: { en: "In delivery", ar: "قيد التنفيذ" },
  DONE: { en: "Delivered", ar: "منجز" },
  DROPPED: { en: "Dropped", ar: "مستبعد" },
};

export const HEALTH_LABEL: Record<Health, L> = {
  NOT_STARTED: { en: "Not started", ar: "لم يبدأ" },
  ON_TRACK: { en: "On track", ar: "على المسار" },
  AT_RISK: { en: "At risk", ar: "معرض للخطر" },
  OFF_TRACK: { en: "Off track", ar: "خارج المسار" },
  DONE: { en: "Delivered", ar: "منجز" },
  DROPPED: { en: "Dropped", ar: "مستبعد" },
};

export const HEALTH_COLOR: Record<Health, string> = { NOT_STARTED: "#8c8a83", ON_TRACK: "#2e8540", AT_RISK: "#c07a12", OFF_TRACK: "#b5453a", DONE: "#2f62a6", DROPPED: "#b9b6ad" };

export const ROLE_LABEL: Record<Role, L> = {
  VIEWER: { en: "Viewer", ar: "مطّلع" },
  PLANNER: { en: "Planner", ar: "مخطط" },
  APPROVER: { en: "Approver", ar: "معتمِد" },
};

/** A portfolio id for an action: governorate + stable action type. Path-safe for the shared store. */
export function itemIdFor(a: Pick<ActionItem, "govId" | "kind">) {
  let h = 2166136261;
  for (let i = 0; i < a.kind.length; i++) h = Math.imul(h ^ a.kind.charCodeAt(i), 16777619);
  return `${a.govId}-${a.kind.split(":")[0]}-${(h >>> 0).toString(36)}`;
}

export const uid = (p: string) => `${p}${Date.now().toString(36)}${Math.random().toString(36).slice(2, 7)}`;

export const isoDay = (d: Date) => d.toISOString().slice(0, 10);
const addMonths = (d: Date, m: number) => { const x = new Date(d); x.setMonth(x.getMonth() + m); return x; };

const MILESTONE_MONTHS: Record<Horizon, number[]> = { IMMEDIATE: [1, 3, 6, 12], SHORT: [3, 9, 18, 36], LONG: [6, 18, 48, 120] };
const MILESTONE_TITLES: L[] = [
  { en: "Business case and costing approved", ar: "اعتماد دراسة الجدوى والكلفة" },
  { en: "Funding secured, procurement launched", ar: "تأمين التمويل وطرح العطاءات" },
  { en: "Implementation under way", ar: "بدء التنفيذ" },
  { en: "Delivered and target verified", ar: "الإنجاز والتحقق من المستهدف" },
];

export function defaultMilestones(h: Horizon, start: Date): Milestone[] {
  return MILESTONE_MONTHS[h].map((m, i) => ({ id: `m${i + 1}`, title: MILESTONE_TITLES[i], due: isoDay(addMonths(start, m)), done: false }));
}

export function itemFromAction(a: ActionItem, by: Actor, now = new Date()): PortfolioItem {
  const at = now.toISOString();
  return {
    id: itemIdFor(a), kind: a.kind, govId: a.govId, sector: a.sector, severity: a.severity, horizon: a.horizon,
    title: a.title, rationale: a.rationale, target: a.kpi, lead: a.lead, costM: Math.round(a.costM * 10) / 10, beneficiaries: a.beneficiaries, href: a.href,
    stage: "PROPOSED", owner: a.lead.en, milestones: defaultMilestones(a.horizon, now),
    kpi: { unit: "% of target delivered", baseline: 0, target: 100, readings: [] },
    spentM: 0, createdAt: at, createdBy: by, updatedAt: at,
  };
}

export function stageOf(item: PortfolioItem, approvals: Record<string, Approval>): Stage {
  if (item.stage !== "PROPOSED") return item.stage;
  return approvals[item.id]?.decision === "APPROVED" ? "APPROVED" : "PROPOSED";
}

export function kpiProgress(item: PortfolioItem) {
  const r = item.kpi.readings;
  const latest = r.length ? r[r.length - 1].value : item.kpi.baseline;
  const span = item.kpi.target - item.kpi.baseline;
  return span === 0 ? 0 : Math.max(0, Math.min(1, (latest - item.kpi.baseline) / span));
}

/** Share of the delivery window elapsed (creation → last milestone). */
export function expectedProgress(item: PortfolioItem, today = new Date()) {
  const start = new Date(item.createdAt).getTime();
  const end = Math.max(...item.milestones.map((m) => new Date(m.due).getTime()), start + 1);
  return Math.max(0, Math.min(1, (today.getTime() - start) / (end - start)));
}

export function overdue(item: PortfolioItem, today = new Date()) {
  const t = isoDay(today);
  return item.milestones.filter((m) => !m.done && m.due < t);
}

export function nextMilestone(item: PortfolioItem) {
  return [...item.milestones].filter((m) => !m.done).sort((a, b) => a.due.localeCompare(b.due))[0] ?? null;
}

/**
 * Delivery health, rule-based and transparent: off track with two or more overdue milestones or
 * progress more than 30 points behind the time elapsed; at risk with one overdue milestone or more
 * than 15 points behind; otherwise on track.
 */
export function healthOf(item: PortfolioItem, approvals: Record<string, Approval>, today = new Date()): Health {
  const s = stageOf(item, approvals);
  if (s === "DONE") return "DONE";
  if (s === "DROPPED") return "DROPPED";
  if (s === "PROPOSED") return "NOT_STARTED";
  const od = overdue(item, today).length;
  const gap = expectedProgress(item, today) - kpiProgress(item);
  if (od >= 2 || gap > 0.3) return "OFF_TRACK";
  if (od === 1 || gap > 0.15) return "AT_RISK";
  return "ON_TRACK";
}

export function versionRows(d: DeliveryData, today = new Date()): VersionRow[] {
  return Object.values(d.items).map((i) => ({ id: i.id, title: i.title, govId: i.govId, sector: i.sector, stage: stageOf(i, d.approvals), health: healthOf(i, d.approvals, today), costM: i.costM, progress: Math.round(kpiProgress(i) * 100) / 100 }));
}

export interface VersionDiff {
  added: VersionRow[];
  removed: VersionRow[];
  changed: { now: VersionRow; then: VersionRow }[];
  costDelta: number;
}

export function diffVersions(then: VersionRow[], now: VersionRow[]): VersionDiff {
  const a = new Map(then.map((r) => [r.id, r]));
  const b = new Map(now.map((r) => [r.id, r]));
  const added = now.filter((r) => !a.has(r.id));
  const removed = then.filter((r) => !b.has(r.id));
  const changed = now.filter((r) => a.has(r.id)).map((r) => ({ now: r, then: a.get(r.id)! })).filter((x) => x.now.stage !== x.then.stage || x.now.health !== x.then.health || Math.abs(x.now.progress - x.then.progress) >= 0.01);
  const cost = (rs: VersionRow[]) => rs.filter((r) => r.stage !== "DROPPED").reduce((s, r) => s + r.costM, 0);
  return { added, removed, changed, costDelta: cost(now) - cost(then) };
}

/**
 * A demonstration portfolio: the highest-priority actions (at most two per sector), back-dated
 * 4–16 months with simulated milestone and KPI progress so the tracker can be shown with content.
 * Everything it creates is flagged `demo` and labelled as simulated in the interface.
 */
export function demoPortfolio(actions: ActionItem[], by: Actor, today = new Date()) {
  const per: Record<string, number> = {};
  const picked = [...actions].sort((a, b) => b.score - a.score).filter((a) => { per[a.sector] = (per[a.sector] ?? 0) + 1; return per[a.sector] <= 2; }).slice(0, 14);
  let seed = 7;
  const rnd = () => { seed = (seed * 16807) % 2147483647; return seed / 2147483647; };
  const items: PortfolioItem[] = [];
  const approvals: Approval[] = [];
  const events: AuditEvent[] = [];
  picked.forEach((a, i) => {
    const proposedOnly = i >= picked.length - 3;
    const approvedOnly = i === 2 || i === 7;
    const ageMonths = proposedOnly ? 0 : approvedOnly ? 1 : 4 + Math.floor(rnd() * 12);
    const start = proposedOnly ? new Date(today.getTime() - (5 + i) * 864e5) : addMonths(today, -ageMonths);
    const it = itemFromAction(a, by, start);
    it.demo = true;
    if (approvedOnly) {
      approvals.push({ itemId: it.id, decision: "APPROVED", note: "Demo approval", at: addMonths(start, 0.5).toISOString(), by });
      events.push({ id: uid("e"), itemId: it.id, kind: "APPROVED", detail: "Demo approval", at: approvals[approvals.length - 1].at, by });
    } else if (!proposedOnly) {
      approvals.push({ itemId: it.id, decision: "APPROVED", note: "Demo approval", at: addMonths(start, 0.5).toISOString(), by });
      const exp = expectedProgress(it, today);
      const perf = [1.05, 0.95, 1, 0.7, 0.45][i % 5];
      const prog = Math.max(0, Math.min(1, exp * perf));
      const n = Math.max(1, Math.min(5, Math.round(ageMonths / 3)));
      it.kpi.readings = Array.from({ length: n }, (_, k) => ({ at: addMonths(start, ((k + 1) * ageMonths) / (n + 0.2)).toISOString(), value: Math.round(prog * 100 * ((k + 1) / n)), by }));
      const tday = isoDay(today);
      it.milestones = it.milestones.map((m, k) => ({ ...m, done: m.due < tday && (perf >= 0.95 || k === 0 || (perf >= 0.7 && k < 2)), doneAt: m.due < tday ? m.due : undefined }));
      it.stage = prog >= 0.999 ? "DONE" : exp > 0.08 ? "IN_DELIVERY" : "PROPOSED";
      it.spentM = Math.round(it.costM * prog * (0.9 + rnd() * 0.3) * 10) / 10;
      events.push({ id: uid("e"), itemId: it.id, kind: "APPROVED", detail: "Demo approval", at: approvals[approvals.length - 1].at, by });
    }
    events.push({ id: uid("e"), itemId: it.id, kind: "PROPOSED", detail: "", at: it.createdAt, by });
    items.push(it);
  });
  return { items, approvals, events };
}
