// Builds the whole app as ONE self-contained HTML page for hosted sharing (opens on a phone, no server).
// Usage: npm run build:artifact  → artifact/dist/index.html
import { build } from "esbuild";
import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const out = path.join(root, "artifact", "dist");
mkdirSync(out, { recursive: true });

// 0. Route table generated from src/app/*/page.tsx so the hosted build can never miss a module
const appDir = path.join(root, "src/app");
const dirs = readdirSync(appDir).filter((d) => existsSync(path.join(appDir, d, "page.tsx"))).sort();
const ident = (d) => `R_${d.replace(/[^a-z0-9]/gi, "_")}`;
writeFileSync(
  path.join(root, "artifact/routes.generated.ts"),
  `// Generated by artifact/build.mjs — do not edit.\nimport type { ComponentType } from "react";\nimport Home from "@/app/page";\n${dirs.map((d) => `import ${ident(d)} from "@/app/${d}/page";`).join("\n")}\n\nexport const ROUTES: Record<string, ComponentType> = {\n  "/": Home,\n${dirs.map((d) => `  "/${d}": ${ident(d)},`).join("\n")}\n};\n`,
);
console.log(`routes: ${dirs.length + 1}`);

// 1. Tailwind 4 → plain CSS (includes maplibre-gl.css via the @import in globals.css)
const cssIn = path.join(root, "src/app/globals.css");
const { css } = await postcss([tailwind({ base: root, optimize: { minify: true } })]).process(readFileSync(cssIn, "utf8"), { from: cssIn });

// 2. MapLibre worker → one ESM file, later turned into a blob: URL
const worker = await build({
  entryPoints: [path.join(root, "node_modules/maplibre-gl/dist/maplibre-gl-worker.mjs")],
  bundle: true, minify: true, format: "esm", target: "es2022", write: false, logLevel: "warning",
});
const workerSrc = worker.outputFiles[0].text;
// Classic (non-module) worker for the offline file: Chrome refuses module workers from file:// pages.
const classicWorker = await build({
  entryPoints: [path.join(root, "node_modules/maplibre-gl/dist/maplibre-gl-worker.mjs")],
  bundle: true, minify: true, format: "iife", target: "es2022", write: false, logLevel: "error",
});
const classicWorkerSrc = classicWorker.outputFiles[0].text;

// 3. App bundle with Next.js routing swapped for an in-memory router
const app = await build({
  entryPoints: [path.join(root, "artifact/entry.tsx")],
  bundle: true, minify: true, format: "iife", target: "es2022", jsx: "automatic", write: false, logLevel: "warning",
  alias: { "next/link": "./artifact/next-link.tsx", "next/navigation": "./artifact/next-navigation.ts" },
  define: { "process.env.NODE_ENV": '"production"' },
  loader: { ".css": "empty" },
  absWorkingDir: root,
  tsconfig: path.join(root, "tsconfig.json"),
});
const appSrc = app.outputFiles[0].text;

const safe = (s) => s.replace(/<\/script/gi, "<\\/script").replace(/<!--/g, "<\\!--");
const html = `<title>UFUQ Jordan Foresight</title>
<meta name="description" content="UFUQ — Jordan National Foresight & Planning Platform. Prototype; operational data simulated.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=IBM+Plex+Sans:wght@400;500;600;700&display=swap">
<style>:root{color-scheme:light}html,body{background:#f6f4ef;color:#141a24}${css}</style>
<div id="root"></div>
<script>window.__JSC_HOSTED__=true;window.__JSC_MAPLIBRE_WORKER__=new URL("maplibre-gl-worker.cjs",location.href).href;</script>
<script>${safe(appSrc)}</script>
`;
writeFileSync(path.join(out, "index.html"), html);
// the hosted page loads the map worker as its own published file (a classic worker)
writeFileSync(path.join(out, "maplibre-gl-worker.cjs"), classicWorkerSrc);
console.log(`artifact/dist/index.html: ${(html.length / 1024 / 1024).toFixed(2)} MB`);

// Offline copy for a laptop: double-click to open, no install. Real downloads and printing work there.
const offline = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">${html.replace('window.__JSC_HOSTED__=true;window.__JSC_MAPLIBRE_WORKER__=new URL("maplibre-gl-worker.cjs",location.href).href;', () => `window.__JSC_MAPLIBRE_WORKER__=URL.createObjectURL(new Blob([${safe(JSON.stringify(classicWorkerSrc))}],{type:"text/javascript"}))+"#.cjs";`)}</body></html>`.replace('<div id="root">', '</head><body><div id="root">');
writeFileSync(path.join(out, "ufuq-jordan.html"), offline);
console.log(`artifact/dist/ufuq-jordan.html: ${(offline.length / 1024 / 1024).toFixed(2)} MB (offline, double-click to open)`);
