// Generated by artifact/build.mjs — do not edit.
import type { ComponentType } from "react";
import Home from "@/app/page";
import R_action_plans from "@/app/action-plans/page";
import R_ageing from "@/app/ageing/page";
import R_anomalies from "@/app/anomalies/page";
import R_ask from "@/app/ask/page";
import R_briefing from "@/app/briefing/page";
import R_capital from "@/app/capital/page";
import R_census from "@/app/census/page";
import R_climate from "@/app/climate/page";
import R_coverage from "@/app/coverage/page";
import R_decision from "@/app/decision/page";
import R_delivery from "@/app/delivery/page";
import R_early_warning from "@/app/early-warning/page";
import R_education from "@/app/education/page";
import R_enumerators from "@/app/enumerators/page";
import R_field from "@/app/field/page";
import R_futures from "@/app/futures/page";
import R_gis from "@/app/gis/page";
import R_health from "@/app/health/page";
import R_housing from "@/app/housing/page";
import R_housing_need from "@/app/housing-need/page";
import R_infrastructure from "@/app/infrastructure/page";
import R_jobs from "@/app/jobs/page";
import R_labour from "@/app/labour/page";
import R_methodology from "@/app/methodology/page";
import R_migration from "@/app/migration/page";
import R_mobility from "@/app/mobility/page";
import R_nowcast from "@/app/nowcast/page";
import R_pes from "@/app/pes/page";
import R_planning from "@/app/planning/page";
import R_population from "@/app/population/page";
import R_projections from "@/app/projections/page";
import R_quality from "@/app/quality/page";
import R_questionnaire from "@/app/questionnaire/page";
import R_reports from "@/app/reports/page";
import R_robustness from "@/app/robustness/page";
import R_scenarios from "@/app/scenarios/page";
import R_shock from "@/app/shock/page";
import R_signals from "@/app/signals/page";
import R_siting from "@/app/siting/page";
import R_urban_growth from "@/app/urban-growth/page";
import R_water from "@/app/water/page";

export const ROUTES: Record<string, ComponentType> = {
  "/": Home,
  "/action-plans": R_action_plans,
  "/ageing": R_ageing,
  "/anomalies": R_anomalies,
  "/ask": R_ask,
  "/briefing": R_briefing,
  "/capital": R_capital,
  "/census": R_census,
  "/climate": R_climate,
  "/coverage": R_coverage,
  "/decision": R_decision,
  "/delivery": R_delivery,
  "/early-warning": R_early_warning,
  "/education": R_education,
  "/enumerators": R_enumerators,
  "/field": R_field,
  "/futures": R_futures,
  "/gis": R_gis,
  "/health": R_health,
  "/housing": R_housing,
  "/housing-need": R_housing_need,
  "/infrastructure": R_infrastructure,
  "/jobs": R_jobs,
  "/labour": R_labour,
  "/methodology": R_methodology,
  "/migration": R_migration,
  "/mobility": R_mobility,
  "/nowcast": R_nowcast,
  "/pes": R_pes,
  "/planning": R_planning,
  "/population": R_population,
  "/projections": R_projections,
  "/quality": R_quality,
  "/questionnaire": R_questionnaire,
  "/reports": R_reports,
  "/robustness": R_robustness,
  "/scenarios": R_scenarios,
  "/shock": R_shock,
  "/signals": R_signals,
  "/siting": R_siting,
  "/urban-growth": R_urban_growth,
  "/water": R_water,
};
