// Generated once from "Freight Orchestrator — process architecture, levels 0 to 3".
// Addresses and titles are copied verbatim from the document. Do not renumber.
// Proposed additions and deviations live in ./deviations.ts, not here.

export interface ArchitectureEntry {
  id: string;
  title: string;
  /** Level-1 only: accountable actor from the document. */
  actor?: string;
  /** Level-1 only: "First built in" column from the document. */
  phase?: string;
  /** Level-2 entries in processes 10 to 14 carry their activity list here. */
  detail?: string;
}

export const ARCHITECTURE: readonly ArchitectureEntry[] = [
  {"id": "1", "title": "Demand capture and customer management", "actor": "Forwarder desk", "phase": "MVP"},
  {"id": "1.1", "title": "Receive the requirement"},
  {"id": "1.1.1", "title": "Ingest from email, WhatsApp, portal form, phone note or API from the shipper's system"},
  {"id": "1.1.2", "title": "Read attachments: purchase order, packing list, supplier invoice, photos"},
  {"id": "1.1.3", "title": "Extract fields and normalise units, ports, dates and currency"},
  {"id": "1.1.4", "title": "Check completeness against the minimum needed to quote"},
  {"id": "1.1.5", "title": "Ask the shipper for what is missing, and track the wait"},
  {"id": "1.1.6", "title": "Deduplicate against existing requests and revisions"},
  {"id": "1.2", "title": "Classify the cargo"},
  {"id": "1.2.1", "title": "Commodity description and HS code"},
  {"id": "1.2.2", "title": "Pieces, dimensions, weight, volume, stackability, packaging type"},
  {"id": "1.2.3", "title": "Special handling: dangerous goods class and UN number, temperature range, out of gauge, high value"},
  {"id": "1.2.4", "title": "Prohibited, restricted and licence-controlled goods check"},
  {"id": "1.2.5", "title": "Incoterm, so responsibility and cost split are known"},
  {"id": "1.3", "title": "Define the service required"},
  {"id": "1.3.1", "title": "Ready date, required delivery date, hard or soft deadline"},
  {"id": "1.3.2", "title": "Mode preference and exclusions, routing constraints"},
  {"id": "1.3.3", "title": "Target price or budget, and what the customer traded last time"},
  {"id": "1.3.4", "title": "Cargo value, insurance need, security requirements"},
  {"id": "1.4", "title": "Customer master and commercial standing"},
  {"id": "1.4.1", "title": "Create or match the customer account and contacts"},
  {"id": "1.4.2", "title": "Credit limit, payment terms, exposure check"},
  {"id": "1.4.3", "title": "Standing agreements: contract rates, SLAs, named carriers to use or avoid"},
  {"id": "1.4.4", "title": "Notification and approval rules per customer"},
  {"id": "2", "title": "Supply and capacity management", "actor": "Carrier, platform", "phase": "MVP"},
  {"id": "2.1", "title": "Build the supply base"},
  {"id": "2.1.1", "title": "Identify carriers by lane, mode and equipment"},
  {"id": "2.1.2", "title": "Verify licence, insurance, bond, sanctions status"},
  {"id": "2.1.3", "title": "Agree the channel: API, EDI, portal, email, chat"},
  {"id": "2.1.4", "title": "Record coverage, restrictions, service strings and transit norms"},
  {"id": "2.2", "title": "Ingest schedules"},
  {"id": "2.2.1", "title": "Departures, arrivals, port rotations, flight or truck departures"},
  {"id": "2.2.2", "title": "Cut-offs: gate-in, documentation, VGM, dangerous goods"},
  {"id": "2.2.3", "title": "Service changes: blank sailings, omissions, delays, reroutes"},
  {"id": "2.3", "title": "Ingest capacity"},
  {"id": "2.3.1", "title": "Free space per departure, in TEU, kilos or pallet slots"},
  {"id": "2.3.2", "title": "Equipment availability by depot and type, including reefer and special"},
  {"id": "2.3.3", "title": "Contracted allotments and how much is already used"},
  {"id": "2.3.4", "title": "Embargoes, weight limits, commodity restrictions"},
  {"id": "2.4", "title": "Hold and release capacity"},
  {"id": "2.4.1", "title": "Soft hold while a quote is live, with an expiry"},
  {"id": "2.4.2", "title": "Convert hold to booking, or release automatically"},
  {"id": "2.4.3", "title": "Overbooking and roll-over rules"},
  {"id": "2.5", "title": "Monitor supply health"},
  {"id": "2.5.1", "title": "Data freshness and feed uptime per carrier"},
  {"id": "2.5.2", "title": "Fall back to email or portal when a feed is stale"},
  {"id": "2.5.3", "title": "Flag lanes where supply is thin before customers feel it"},
  {"id": "3", "title": "Rate and cost management", "actor": "Forwarder desk, carrier", "phase": "MVP"},
  {"id": "3.1", "title": "Capture rates"},
  {"id": "3.1.1", "title": "Contract and tender rates, with validity and volume commitments"},
  {"id": "3.1.2", "title": "Spot replies to a specific request"},
  {"id": "3.1.3", "title": "Rate sheets in spreadsheet or PDF, and API or EDI tariffs"},
  {"id": "3.2", "title": "Normalise rates"},
  {"id": "3.2.1", "title": "Map charge names onto one charge-code dictionary"},
  {"id": "3.2.2", "title": "Convert currency, unit basis and container type"},
  {"id": "3.2.3", "title": "Separate freight, surcharges, local charges and inland legs"},
  {"id": "3.2.4", "title": "Record what is included and what is not"},
  {"id": "3.3", "title": "Hold the full cost picture"},
  {"id": "3.3.1", "title": "Origin charges, destination charges, customs, inland, delivery"},
  {"id": "3.3.2", "title": "Duty and tax estimate from HS code and value"},
  {"id": "3.3.3", "title": "Free time, demurrage and detention terms as a risk, not a price"},
  {"id": "3.4", "title": "Manage validity"},
  {"id": "3.4.1", "title": "Expiry alerts and automatic re-quote triggers"},
  {"id": "3.4.2", "title": "General rate increases, peak season and seasonal surcharges"},
  {"id": "3.4.3", "title": "Version history: what was valid on the day a quote was given"},
  {"id": "3.5", "title": "Control rate visibility"},
  {"id": "3.5.1", "title": "Rates belong to the desk that negotiated them"},
  {"id": "3.5.2", "title": "Rules for aggregating into benchmarks without exposing any one carrier"},
  {"id": "3.5.3", "title": "Audit of who viewed or exported what"},
  {"id": "4", "title": "Quotation, matching and optimisation", "actor": "Platform", "phase": "MVP"},
  {"id": "4.1", "title": "Issue the RFQ"},
  {"id": "4.1.1", "title": "Choose which carriers to ask, from lane, equipment, reliability and commercial rules"},
  {"id": "4.1.2", "title": "Decide what to reveal: cargo detail yes, customer identity usually not"},
  {"id": "4.1.3", "title": "Format per channel: API call, EDI message, portal entry, email, chat"},
  {"id": "4.1.4", "title": "Set a reply deadline tied to the cut-off, not to office hours"},
  {"id": "4.1.5", "title": "Chase non-responders automatically, then escalate or drop them"},
  {"id": "4.2", "title": "Harvest replies"},
  {"id": "4.2.1", "title": "Collect from every channel into one thread per request"},
  {"id": "4.2.2", "title": "Attribute each reply to carrier, lane, request and sailing"},
  {"id": "4.2.3", "title": "Detect revisions and supersede earlier offers"},
  {"id": "4.2.4", "title": "Handle partial replies: \"space yes, rate later\""},
  {"id": "4.3", "title": "Turn replies into data"},
  {"id": "4.3.1", "title": "Extract rate, equipment, transit, routing, cut-off, validity, conditions"},
  {"id": "4.3.2", "title": "Score confidence per field, not per message"},
  {"id": "4.3.3", "title": "Route low-confidence fields to a person, with the source shown"},
  {"id": "4.3.4", "title": "Capture corrections as labelled training data"},
  {"id": "4.3.5", "title": "Track accuracy per carrier and per format, and flag formats that need a template"},
  {"id": "4.4", "title": "Test feasibility"},
  {"id": "4.4.1", "title": "Physical fit: pallets or pieces against equipment floor, height and payload"},
  {"id": "4.4.2", "title": "Weight and axle limits for the inland legs"},
  {"id": "4.4.3", "title": "Dangerous goods acceptance and segregation rules"},
  {"id": "4.4.4", "title": "Temperature, ventilation and power requirements"},
  {"id": "4.4.5", "title": "Timing: cargo ready date against cut-off, arrival against the customer deadline"},
  {"id": "4.4.6", "title": "Routing and compliance: sanctions, port restrictions, carrier embargoes"},
  {"id": "4.4.7", "title": "Record every rejection with its reason, visible to the desk"},
  {"id": "4.5", "title": "Build the options"},
  {"id": "4.5.1", "title": "Single-mode options per carrier and sailing"},
  {"id": "4.5.2", "title": "Multimodal chains: legs joined with realistic handover times"},
  {"id": "4.5.3", "title": "Consolidation candidates with other shipments on the same lane"},
  {"id": "4.5.4", "title": "Split options: part air, part ocean, or staged deliveries"},
  {"id": "4.5.5", "title": "Total cost build-up per option, door to door"},
  {"id": "4.6", "title": "Score and rank"},
  {"id": "4.6.1", "title": "Normalise price, transit, reliability, emissions and risk"},
  {"id": "4.6.2", "title": "Apply weights: customer preference, preset or desk default"},
  {"id": "4.6.3", "title": "Produce the ranking and the reason the top option won"},
  {"id": "4.6.4", "title": "Show what was excluded and why"},
  {"id": "4.7", "title": "Quote the customer"},
  {"id": "4.7.1", "title": "Apply margin rules: floor, target, customer agreement, approval threshold"},
  {"id": "4.7.2", "title": "Compare against the lane benchmark and estimate the chance of winning"},
  {"id": "4.7.3", "title": "Generate the quote with scope, exclusions, validity and terms"},
  {"id": "4.7.4", "title": "Send through the customer's preferred channel and log delivery"},
  {"id": "4.7.5", "title": "Version and re-quote when rates, space or dates move"},
  {"id": "4.8", "title": "Close the quote"},
  {"id": "4.8.1", "title": "Capture acceptance, rejection or counter-offer"},
  {"id": "4.8.2", "title": "Internal approval where margin or value crosses a threshold"},
  {"id": "4.8.3", "title": "Expire unaccepted quotes and release held space"},
  {"id": "4.8.4", "title": "Record win or loss with the reason and the competing price if known"},
  {"id": "5", "title": "Booking and order management", "actor": "Forwarder desk, carrier", "phase": "Phase 2"},
  {"id": "5.1", "title": "Place the booking"},
  {"id": "5.1.1", "title": "Send the booking on the carrier's channel and capture the reference"},
  {"id": "5.1.2", "title": "Reconcile the confirmation against the quote: rate, vessel, dates, equipment"},
  {"id": "5.1.3", "title": "Escalate mismatches before they reach the customer"},
  {"id": "5.2", "title": "Plan equipment and pickup"},
  {"id": "5.2.1", "title": "Empty release, depot, container number and seal"},
  {"id": "5.2.2", "title": "Haulier assignment, loading window, site access rules"},
  {"id": "5.2.3", "title": "Loading plan and weighing, including VGM"},
  {"id": "5.3", "title": "Plan the deadlines"},
  {"id": "5.3.1", "title": "Working backwards from cut-offs: gate-in, documents, dangerous goods"},
  {"id": "5.3.2", "title": "Shipping instructions submitted and confirmed"},
  {"id": "5.3.3", "title": "Countdown alerts to whoever must act"},
  {"id": "5.4", "title": "Change and cancel"},
  {"id": "5.4.1", "title": "Amend dates, volumes or equipment"},
  {"id": "5.4.2", "title": "Roll-over and re-booking after a missed sailing or a blank"},
  {"id": "5.4.3", "title": "Cancellation, no-show and dead-freight charges"},
  {"id": "5.5", "title": "Manage the order book"},
  {"id": "5.5.1", "title": "Consolidation groups and their cut-off"},
  {"id": "5.5.2", "title": "Allotment usage against commitments"},
  {"id": "5.5.3", "title": "Forecast of bookings per lane for carriers"},
  {"id": "6", "title": "Documentation and compliance", "actor": "Forwarder desk, partner", "phase": "Phase 2"},
  {"id": "6.1", "title": "Generate documents"},
  {"id": "6.1.1", "title": "Bill of lading or electronic bill, air waybill, CMR, delivery note"},
  {"id": "6.1.2", "title": "Labels, manifests, packing declarations"},
  {"id": "6.1.3", "title": "House versus master documents where the desk consolidates"},
  {"id": "6.2", "title": "Collect and validate"},
  {"id": "6.2.1", "title": "Commercial invoice, packing list, certificate of origin, certificates and permits"},
  {"id": "6.2.2", "title": "Dangerous goods declaration and safety data sheet"},
  {"id": "6.2.3", "title": "Cross-check values, weights and parties against the booking"},
  {"id": "6.2.4", "title": "Chase missing documents against the filing deadline"},
  {"id": "6.3", "title": "File with authorities"},
  {"id": "6.3.1", "title": "Export declaration at origin"},
  {"id": "6.3.2", "title": "Pre-arrival and import declarations at destination"},
  {"id": "6.3.3", "title": "Duty and tax calculation and payment"},
  {"id": "6.3.4", "title": "Inspections, holds and release"},
  {"id": "6.4", "title": "Screen for compliance"},
  {"id": "6.4.1", "title": "Sanctions and denied-party screening of all parties"},
  {"id": "6.4.2", "title": "Dual-use and licence checks"},
  {"id": "6.4.3", "title": "Country and commodity embargoes"},
  {"id": "6.5", "title": "Distribute and keep"},
  {"id": "6.5.1", "title": "Send to shipper, consignee, bank, broker and carrier"},
  {"id": "6.5.2", "title": "Release rules: originals, telex release, electronic surrender"},
  {"id": "6.5.3", "title": "Retention, retrieval and audit trail"},
  {"id": "7", "title": "Execution, visibility and exceptions", "actor": "Platform, carrier", "phase": "Phase 2"},
  {"id": "7.1", "title": "Track milestones"},
  {"id": "7.1.1", "title": "Collect events: gate-in, loaded, departed, transshipped, arrived, discharged, cleared, delivered"},
  {"id": "7.1.2", "title": "Sources: carrier feeds, terminal systems, vessel position, partner updates, driver app, sensors"},
  {"id": "7.1.3", "title": "Reconcile conflicting or late events into one timeline"},
  {"id": "7.2", "title": "Predict and re-plan"},
  {"id": "7.2.1", "title": "Estimated arrival with a confidence level"},
  {"id": "7.2.2", "title": "Knock-on effects on inland legs, appointments and the customer deadline"},
  {"id": "7.2.3", "title": "Re-plan options when the prediction breaks the promise"},
  {"id": "7.3", "title": "Detect exceptions"},
  {"id": "7.3.1", "title": "Delay, blank sailing, roll-over, missed connection"},
  {"id": "7.3.2", "title": "Missing or rejected documents, customs hold, inspection"},
  {"id": "7.3.3", "title": "Damage, loss, temperature excursion, seal break"},
  {"id": "7.3.4", "title": "Demurrage and detention risk before charges start"},
  {"id": "7.4", "title": "Resolve exceptions"},
  {"id": "7.4.1", "title": "Playbook per exception type, with the owner and the clock"},
  {"id": "7.4.2", "title": "Re-route, re-book, expedite or accept with a revised promise"},
  {"id": "7.4.3", "title": "Escalation path and customer approval where cost changes"},
  {"id": "7.4.4", "title": "Record cause, cost and who absorbed it"},
  {"id": "7.5", "title": "Keep everyone informed"},
  {"id": "7.5.1", "title": "Milestone notifications by party and preference"},
  {"id": "7.5.2", "title": "Proactive warnings, not status requests answered late"},
  {"id": "7.5.3", "title": "Arrival notice, delivery booking, proof of delivery and closure"},
  {"id": "8", "title": "Settlement, payments and disputes", "actor": "Forwarder desk, platform", "phase": "Phase 2"},
  {"id": "8.1", "title": "Accrue the cost"},
  {"id": "8.1.1", "title": "Expected charges per shipment from the accepted quote"},
  {"id": "8.1.2", "title": "Accrue as events happen, so margin is known before invoices arrive"},
  {"id": "8.2", "title": "Audit the carrier invoice"},
  {"id": "8.2.1", "title": "Match invoice to quote and booking, line by line"},
  {"id": "8.2.2", "title": "Apply tolerance rules and approve what is within them"},
  {"id": "8.2.3", "title": "Flag charges that were never agreed, with the evidence attached"},
  {"id": "8.2.4", "title": "Validate demurrage and detention against free time actually used"},
  {"id": "8.3", "title": "Invoice the customer"},
  {"id": "8.3.1", "title": "Build the invoice from the quote plus approved extras"},
  {"id": "8.3.2", "title": "Currency, exchange rate and tax treatment per jurisdiction"},
  {"id": "8.3.3", "title": "Consolidated and scheduled invoicing per customer agreement"},
  {"id": "8.3.4", "title": "Credit notes and corrections"},
  {"id": "8.4", "title": "Move the money"},
  {"id": "8.4.1", "title": "Collect from the customer, including escrow funding where used"},
  {"id": "8.4.2", "title": "Release to the carrier on the agreed trigger, usually proof of delivery"},
  {"id": "8.4.3", "title": "Pay partners their fees"},
  {"id": "8.4.4", "title": "Dunning, overdue ladders and credit holds"},
  {"id": "8.4.5", "title": "Optional financing: early payment to carriers, extended terms to shippers"},
  {"id": "8.5", "title": "Disputes and claims"},
  {"id": "8.5.1", "title": "Charge disputes with the carrier, and the clock on them"},
  {"id": "8.5.2", "title": "Cargo loss and damage claims, with evidence from tracking and documents"},
  {"id": "8.5.3", "title": "Insurance claims and recoveries"},
  {"id": "8.5.4", "title": "Write-offs and the lesson recorded against the carrier score"},
  {"id": "8.6", "title": "Close the shipment"},
  {"id": "8.6.1", "title": "Final profit and loss per shipment"},
  {"id": "8.6.2", "title": "Margin leakage analysis by cause"},
  {"id": "8.6.3", "title": "Feed the result back into pricing guidance"},
  {"id": "9", "title": "Ancillary and partner services", "actor": "Service partner", "phase": "Phase 6"},
  {"id": "9.1", "title": "Maintain the service catalogue"},
  {"id": "9.1.1", "title": "Service types, coverage by country and port, prices and lead times"},
  {"id": "9.1.2", "title": "Which services attach automatically to which shipment type"},
  {"id": "9.2", "title": "Dispatch jobs"},
  {"id": "9.2.1", "title": "Create the job with documents and data already attached"},
  {"id": "9.2.2", "title": "Offer, accept and assign, with a deadline"},
  {"id": "9.2.3", "title": "Fall back to a second partner when a job is not accepted in time"},
  {"id": "9.3", "title": "Quote and contract the service"},
  {"id": "9.3.1", "title": "Fixed fee, tariff or quoted per job"},
  {"id": "9.3.2", "title": "Service level agreed and visible to the desk"},
  {"id": "9.4", "title": "Settle with partners"},
  {"id": "9.4.1", "title": "Partner invoice or self-billing"},
  {"id": "9.4.2", "title": "Revenue share or platform fee deducted"},
  {"id": "9.5", "title": "Manage partner performance"},
  {"id": "9.5.1", "title": "Turnaround time, rejection rate, error rate"},
  {"id": "9.5.2", "title": "Ranking and removal rules"},
  {"id": "10", "title": "Onboarding and network growth", "actor": "Platform", "phase": "MVP"},
  {"id": "10.1", "title": "Onboard a forwarder desk", "detail": "contract, users and roles, mailbox connection, rate sheet import, customer and carrier import, desk rules, training, first live quote"},
  {"id": "10.2", "title": "Onboard a shipper", "detail": "account, contacts, incoterms and templates, credit, notification preferences"},
  {"id": "10.3", "title": "Onboard a carrier", "detail": "channels, lanes, equipment, rate cards, permissions, test message, go live"},
  {"id": "10.4", "title": "Onboard a service partner", "detail": "licence and insurance check, coverage, fees, service levels"},
  {"id": "10.5", "title": "Migrate history", "detail": "past quotes, rates, customers and shipments, so benchmarks work on day one"},
  {"id": "10.6", "title": "Launch a lane or mode", "detail": "supply mapped, rules written, documents templated, pilot customer named, exit criteria agreed"},
  {"id": "11", "title": "Data, intelligence and learning", "actor": "Platform", "phase": "MVP"},
  {"id": "11.1", "title": "Master data", "detail": "ports and locations, carriers, vessels and services, equipment types, charge codes, HS codes, currencies, calendars and holidays"},
  {"id": "11.2", "title": "Benchmarks", "detail": "rate index by lane and equipment, transit norms, aggregation and anonymisation rules"},
  {"id": "11.3", "title": "Scoring", "detail": "carrier reliability, quote accuracy, response speed, claim rate; desk and partner performance"},
  {"id": "11.4", "title": "Forecasting", "detail": "rate direction, demand per lane, capacity crunches, disruption risk"},
  {"id": "11.5", "title": "Commercial analytics", "detail": "win and loss, price gaps, margin leakage, pricing guidance"},
  {"id": "11.6", "title": "Model operations", "detail": "training sets built from corrections, evaluation against held-out replies, accuracy thresholds per format, drift monitoring, model and prompt versioning, rollback"},
  {"id": "11.7", "title": "Emissions accounting", "detail": "emissions per leg and per shipment, method stated, customer reporting"},
  {"id": "12", "title": "Governance, security and access", "actor": "Platform", "phase": "MVP"},
  {"id": "12.1", "title": "Identity and access", "detail": "organisations, roles, personas, single sign-on, session control"},
  {"id": "12.2", "title": "Data permissions", "detail": "the who-sees-what matrix for rates, bids, margin and cargo detail, enforced in one place"},
  {"id": "12.3", "title": "Audit and traceability", "detail": "every automated decision, override and export logged and replayable"},
  {"id": "12.4", "title": "Privacy and retention", "detail": "personal data, residency rules, retention and deletion"},
  {"id": "12.5", "title": "Security operations", "detail": "secrets, access reviews, penetration testing, vulnerability and incident response"},
  {"id": "12.6", "title": "Legal and regulatory", "detail": "terms of service, liability position (software provider versus contracting carrier), professional indemnity and cargo liability insurance, licences per market"},
  {"id": "13", "title": "Support, service levels and incidents", "actor": "Platform", "phase": "MVP"},
  {"id": "13.1", "title": "Help desk", "detail": "channels, ticketing, severity, ownership"},
  {"id": "13.2", "title": "Service levels", "detail": "response and resolution targets, uptime, extraction accuracy, measured and reported"},
  {"id": "13.3", "title": "Incidents", "detail": "detection, manual fallback so quoting never stops, communication, post-incident review"},
  {"id": "13.4", "title": "Change management", "detail": "configuration versus code, release notes, training on changes"},
  {"id": "13.5", "title": "Feedback loop", "detail": "tickets and corrections feeding the product backlog"},
  {"id": "14", "title": "Commercial operations", "actor": "Platform", "phase": "MVP"},
  {"id": "14.1", "title": "Pricing and packaging", "detail": "seats, booking fees, premium analytics, partner share, pilot terms"},
  {"id": "14.2", "title": "Metering", "detail": "quotes, bookings, seats and API calls counted reliably"},
  {"id": "14.3", "title": "Billing", "detail": "subscription invoicing, usage billing, taxes, collections"},
  {"id": "14.4", "title": "Customer lifecycle", "detail": "pilot to paid conversion, renewals, expansion, churn and win-back"},
  {"id": "14.5", "title": "Channel and partnerships", "detail": "associations, port communities, software resellers, referral terms"},
];
