import { DEVIATIONS } from "./deviations";
import { ALL_PROCESSES, IMPLEMENTATIONS } from "./registry";

const BADGE = { built: "built", partial: "partial", stub: "stub", not_started: "" } as const;

export function renderProcessMap(): string {
  const byId = new Map(IMPLEMENTATIONS.map((i) => [i.id, i]));
  const lines = [
    "# Process map",
    "",
    "Generated by `npm run process-map` from `src/processes/`. Do not edit by hand.",
    "",
    "Every address from the process document, plus the additions in `src/processes/deviations.ts` (marked *added*).",
    "Status: **built** (done and tested), **partial** (some of it done and tested), **stub** (data model and state machine only), blank (not started).",
    "",
    "| Address | Process | Status | Code | Tests |",
    "| --- | --- | --- | --- | --- |",
  ];
  for (const p of ALL_PROCESSES) {
    const i = byId.get(p.id);
    const depth = p.id.split(".").length - 1;
    const title = `${"&nbsp;&nbsp;".repeat(depth * 2)}${depth === 0 ? `**${p.title}**` : p.title}${p.added ? " *(added)*" : ""}`;
    const code = i?.modules.map((m) => `\`${m}\``).join("<br>") ?? "";
    const tests = i?.tests.map((m) => `\`${m}\``).join("<br>") ?? "";
    const status = i ? BADGE[i.status] + (i.note ? ` — ${i.note}` : "") : "";
    lines.push(`| ${p.id} | ${title} | ${status} | ${code} | ${tests} |`);
  }
  lines.push("", "## Differences from the process document", "", "| Ref | Change | Why |", "| --- | --- | --- |");
  for (const d of DEVIATIONS) lines.push(`| ${d.ref} | ${d.summary} | ${d.why} |`);
  return lines.join("\n") + "\n";
}
