// Generated by scripts/fetch-open-data.mjs — do not edit by hand.
// Jordan series from open mirrors of World Bank WDI and Our World in Data (see sources[]).
import type { OpenData } from "./openData";

export const OPEN_DATA_SNAPSHOT: OpenData = {
 "fetchedAt": "2026-10-02T11:42:48.573Z",
 "sources": [
  {
   "id": "OPEN_WB_GDP",
   "url": "https://raw.githubusercontent.com/datasets/gdp/main/data/gdp.csv",
   "licence": "ODC-PDDL-1.0 (World Bank WDI NY.GDP.MKTP.CD mirror)",
   "rows": 59,
   "firstYear": 1965,
   "lastYear": 2023,
   "sha256": "8d84ef6bcaccf740"
  },
  {
   "id": "OPEN_WB_POP",
   "url": "https://raw.githubusercontent.com/datasets/population/main/data/population.csv",
   "licence": "ODC-PDDL-1.0 (World Bank WDI SP.POP.TOTL mirror)",
   "rows": 66,
   "firstYear": 1960,
   "lastYear": 2025,
   "sha256": "2c697c3e668c8cb0"
  },
  {
   "id": "OPEN_WB_CPI",
   "url": "https://raw.githubusercontent.com/datasets/inflation/main/data/inflation-consumer.csv",
   "licence": "ODC-PDDL-1.0 (World Bank WDI FP.CPI.TOTL.ZG mirror)",
   "rows": 47,
   "firstYear": 1977,
   "lastYear": 2023,
   "sha256": "b47dbd6a5d44c4ea"
  },
  {
   "id": "OPEN_OWID_ENERGY",
   "url": "https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv",
   "licence": "CC BY 4.0 (Our World in Data, based on Ember and the Energy Institute)",
   "rows": 25,
   "firstYear": 2000,
   "lastYear": 2024,
   "sha256": "266f2e2baad79753"
  }
 ],
 "gdpUsd": [
  {
   "year": 1965,
   "value": 599759760.096096
  },
  {
   "year": 1966,
   "value": 657999736.8001053
  },
  {
   "year": 1967,
   "value": 631679747.328101
  },
  {
   "year": 1968,
   "value": 561119775.5520898
  },
  {
   "year": 1969,
   "value": 698879720.4481119
  },
  {
   "year": 1970,
   "value": 639519744.1921023
  },
  {
   "year": 1971,
   "value": 678159728.7361085
  },
  {
   "year": 1972,
   "value": 788479684.6081262
  },
  {
   "year": 1973,
   "value": 943783839.7180518
  },
  {
   "year": 1974,
   "value": 1197483948.6854687
  },
  {
   "year": 1975,
   "value": 1363073497.7735527
  },
  {
   "year": 1976,
   "value": 1708521219.4600327
  },
  {
   "year": 1977,
   "value": 2096778602.1678457
  },
  {
   "year": 1978,
   "value": 2602208588.9570556
  },
  {
   "year": 1979,
   "value": 3271368780.6534743
  },
  {
   "year": 1980,
   "value": 3910044474.28044
  },
  {
   "year": 1981,
   "value": 4383944702.859582
  },
  {
   "year": 1982,
   "value": 4681240992.703381
  },
  {
   "year": 1983,
   "value": 4920692190.9556875
  },
  {
   "year": 1984,
   "value": 4967162160.404718
  },
  {
   "year": 1985,
   "value": 4993601520.430789
  },
  {
   "year": 1986,
   "value": 6402050484.904248
  },
  {
   "year": 1987,
   "value": 6756209762.482309
  },
  {
   "year": 1988,
   "value": 6277451829.053252
  },
  {
   "year": 1989,
   "value": 4221373673.804684
  },
  {
   "year": 1990,
   "value": 4160087507.8347235
  },
  {
   "year": 1991,
   "value": 4344467193.250948
  },
  {
   "year": 1992,
   "value": 5310833193.590049
  },
  {
   "year": 1993,
   "value": 5606400221.692687
  },
  {
   "year": 1994,
   "value": 6236295978.245313
  },
  {
   "year": 1995,
   "value": 6727597031.96347
  },
  {
   "year": 1996,
   "value": 6927503526.093089
  },
  {
   "year": 1997,
   "value": 7245839210.1551485
  },
  {
   "year": 1998,
   "value": 7912270803.949224
  },
  {
   "year": 1999,
   "value": 8149929478.138224
  },
  {
   "year": 2000,
   "value": 8460789844.851905
  },
  {
   "year": 2001,
   "value": 8975814652.819601
  },
  {
   "year": 2002,
   "value": 9582510578.279266
  },
  {
   "year": 2003,
   "value": 10195627644.569817
  },
  {
   "year": 2004,
   "value": 11411706629.055008
  },
  {
   "year": 2005,
   "value": 12588998589.562765
  },
  {
   "year": 2006,
   "value": 15056981664.315939
  },
  {
   "year": 2007,
   "value": 17110437235.543018
  },
  {
   "year": 2008,
   "value": 22658715989.330204
  },
  {
   "year": 2009,
   "value": 24537876056.338028
  },
  {
   "year": 2010,
   "value": 27133804225.352116
  },
  {
   "year": 2011,
   "value": 29524149154.92958
  },
  {
   "year": 2012,
   "value": 31634561690.140846
  },
  {
   "year": 2013,
   "value": 34454440140.84507
  },
  {
   "year": 2014,
   "value": 36847643521.12676
  },
  {
   "year": 2015,
   "value": 38587017887.323944
  },
  {
   "year": 2016,
   "value": 39892551126.76057
  },
  {
   "year": 2017,
   "value": 41608435915.49296
  },
  {
   "year": 2018,
   "value": 43370860704.22536
  },
  {
   "year": 2019,
   "value": 44502816901.408455
  },
  {
   "year": 2020,
   "value": 43700383098.59155
  },
  {
   "year": 2021,
   "value": 46296100140.84507
  },
  {
   "year": 2022,
   "value": 48653381830.985916
  },
  {
   "year": 2023,
   "value": 50813642348.674644
  }
 ],
 "population": [
  {
   "year": 1960,
   "value": 853471
  },
  {
   "year": 1961,
   "value": 897591
  },
  {
   "year": 1962,
   "value": 940554
  },
  {
   "year": 1963,
   "value": 984714
  },
  {
   "year": 1964,
   "value": 1035640
  },
  {
   "year": 1965,
   "value": 1099440
  },
  {
   "year": 1966,
   "value": 1178360
  },
  {
   "year": 1967,
   "value": 1271183
  },
  {
   "year": 1968,
   "value": 1372460
  },
  {
   "year": 1969,
   "value": 1473100
  },
  {
   "year": 1970,
   "value": 1565163
  },
  {
   "year": 1971,
   "value": 1645145
  },
  {
   "year": 1972,
   "value": 1714555
  },
  {
   "year": 1973,
   "value": 1778094
  },
  {
   "year": 1974,
   "value": 1839182
  },
  {
   "year": 1975,
   "value": 1899055
  },
  {
   "year": 1976,
   "value": 1958177
  },
  {
   "year": 1977,
   "value": 2019002
  },
  {
   "year": 1978,
   "value": 2083595
  },
  {
   "year": 1979,
   "value": 2153882
  },
  {
   "year": 1980,
   "value": 2234186
  },
  {
   "year": 1981,
   "value": 2325517
  },
  {
   "year": 1982,
   "value": 2426927
  },
  {
   "year": 1983,
   "value": 2537307
  },
  {
   "year": 1984,
   "value": 2654688
  },
  {
   "year": 1985,
   "value": 2778810
  },
  {
   "year": 1986,
   "value": 2909887
  },
  {
   "year": 1987,
   "value": 3047634
  },
  {
   "year": 1988,
   "value": 3193039
  },
  {
   "year": 1989,
   "value": 3349627
  },
  {
   "year": 1990,
   "value": 3621908
  },
  {
   "year": 1991,
   "value": 3915149
  },
  {
   "year": 1992,
   "value": 4127693
  },
  {
   "year": 1993,
   "value": 4348020
  },
  {
   "year": 1994,
   "value": 4561406
  },
  {
   "year": 1995,
   "value": 4752096
  },
  {
   "year": 1996,
   "value": 4912516
  },
  {
   "year": 1997,
   "value": 5046285
  },
  {
   "year": 1998,
   "value": 5164284
  },
  {
   "year": 1999,
   "value": 5276444
  },
  {
   "year": 2000,
   "value": 5386945
  },
  {
   "year": 2001,
   "value": 5498894
  },
  {
   "year": 2002,
   "value": 5616066
  },
  {
   "year": 2003,
   "value": 5741828
  },
  {
   "year": 2004,
   "value": 5882061
  },
  {
   "year": 2005,
   "value": 6029587
  },
  {
   "year": 2006,
   "value": 6427371
  },
  {
   "year": 2007,
   "value": 6827227
  },
  {
   "year": 2008,
   "value": 6989866
  },
  {
   "year": 2009,
   "value": 7141753
  },
  {
   "year": 2010,
   "value": 7297043
  },
  {
   "year": 2011,
   "value": 7480424
  },
  {
   "year": 2012,
   "value": 7587127
  },
  {
   "year": 2013,
   "value": 7991809
  },
  {
   "year": 2014,
   "value": 8791710
  },
  {
   "year": 2015,
   "value": 9544729
  },
  {
   "year": 2016,
   "value": 10006367
  },
  {
   "year": 2017,
   "value": 10234226
  },
  {
   "year": 2018,
   "value": 10462306
  },
  {
   "year": 2019,
   "value": 10671891
  },
  {
   "year": 2020,
   "value": 10865228
  },
  {
   "year": 2021,
   "value": 11066356
  },
  {
   "year": 2022,
   "value": 11256263
  },
  {
   "year": 2023,
   "value": 11439213
  },
  {
   "year": 2024,
   "value": 11552876
  },
  {
   "year": 2025,
   "value": 11520684
  }
 ],
 "inflation": [
  {
   "year": 1977,
   "value": 12.3938335895359
  },
  {
   "year": 1978,
   "value": 0.448662637372735
  },
  {
   "year": 1979,
   "value": 2.26433137301889
  },
  {
   "year": 1980,
   "value": 6.63763027888631
  },
  {
   "year": 1981,
   "value": 6.12338530533319
  },
  {
   "year": 1982,
   "value": 6.43212145274833
  },
  {
   "year": 1983,
   "value": 10.7301456603332
  },
  {
   "year": 1984,
   "value": 2.49156453400215
  },
  {
   "year": 1985,
   "value": 6.05996991063435
  },
  {
   "year": 1986,
   "value": 7.76430529168408
  },
  {
   "year": 1987,
   "value": -0.255303258488595
  },
  {
   "year": 1988,
   "value": 1.26995012150029
  },
  {
   "year": 1989,
   "value": 15.6373185566697
  },
  {
   "year": 1990,
   "value": 14.1512702228617
  },
  {
   "year": 1991,
   "value": 5.43525695025883
  },
  {
   "year": 1992,
   "value": 6.7386811523716
  },
  {
   "year": 1993,
   "value": 2.96897921969565
  },
  {
   "year": 1994,
   "value": 6.8617322590588
  },
  {
   "year": 1995,
   "value": 1.88459153084248
  },
  {
   "year": 1996,
   "value": 2.04656660644706
  },
  {
   "year": 1997,
   "value": 1.24555949988834
  },
  {
   "year": 1998,
   "value": 6.00440267503002
  },
  {
   "year": 1999,
   "value": -0.373208627520512
  },
  {
   "year": 2000,
   "value": -0.413869577569187
  },
  {
   "year": 2001,
   "value": 0.773909402226451
  },
  {
   "year": 2002,
   "value": 0.924509731059914
  },
  {
   "year": 2003,
   "value": 2.14726310376403
  },
  {
   "year": 2004,
   "value": 3.09507950152911
  },
  {
   "year": 2005,
   "value": 2.00647430326822
  },
  {
   "year": 2006,
   "value": 10.6494515467628
  },
  {
   "year": 2007,
   "value": 5.04891837327762
  },
  {
   "year": 2008,
   "value": 23.6246844255135
  },
  {
   "year": 2009,
   "value": 3.16159648072517
  },
  {
   "year": 2010,
   "value": 8.07745609713074
  },
  {
   "year": 2011,
   "value": 5.91051095801734
  },
  {
   "year": 2012,
   "value": 4.60681522593885
  },
  {
   "year": 2013,
   "value": 6.1436238894444
  },
  {
   "year": 2014,
   "value": 3.44532356315609
  },
  {
   "year": 2015,
   "value": 2.16975211695323
  },
  {
   "year": 2016,
   "value": 1.36200664175068
  },
  {
   "year": 2017,
   "value": 1.78355010971296
  },
  {
   "year": 2018,
   "value": 2.27304680591043
  },
  {
   "year": 2019,
   "value": 0.844355656854063
  },
  {
   "year": 2020,
   "value": -0.708587970279524
  },
  {
   "year": 2021,
   "value": 2.20360600532175
  },
  {
   "year": 2022,
   "value": 2.61607218645355
  },
  {
   "year": 2023,
   "value": 1.79036458654697
  }
 ],
 "electricity": [
  {
   "year": 2000,
   "demandTWh": 7.79,
   "generationTWh": 7.37,
   "renewablesShare": 0.543,
   "solarShare": 0,
   "perCapitaKWh": 1368.122,
   "netImportsTWh": 0.42,
   "ghgMt": 4.85
  },
  {
   "year": 2001,
   "demandTWh": 7.8,
   "generationTWh": 7.54,
   "renewablesShare": 0.531,
   "solarShare": 0,
   "perCapitaKWh": 1371.183,
   "netImportsTWh": 0.26,
   "ghgMt": 4.96
  },
  {
   "year": 2002,
   "demandTWh": 8.44,
   "generationTWh": 8.12,
   "renewablesShare": 0.616,
   "solarShare": 0,
   "perCapitaKWh": 1445.849,
   "netImportsTWh": 0.32,
   "ghgMt": 5.33
  },
  {
   "year": 2003,
   "demandTWh": 9,
   "generationTWh": 8.03,
   "renewablesShare": 0.623,
   "solarShare": 0,
   "perCapitaKWh": 1398.507,
   "netImportsTWh": 0.97,
   "ghgMt": 5.28
  },
  {
   "year": 2004,
   "demandTWh": 9.75,
   "generationTWh": 8.96,
   "renewablesShare": 0.67,
   "solarShare": 0,
   "perCapitaKWh": 1523.274,
   "netImportsTWh": 0.79,
   "ghgMt": 6.01
  },
  {
   "year": 2005,
   "demandTWh": 10.39,
   "generationTWh": 9.65,
   "renewablesShare": 0.622,
   "solarShare": 0,
   "perCapitaKWh": 1600.439,
   "netImportsTWh": 0.74,
   "ghgMt": 6.49
  },
  {
   "year": 2006,
   "demandTWh": 11.58,
   "generationTWh": 11.12,
   "renewablesShare": 0.54,
   "solarShare": 0,
   "perCapitaKWh": 1730.099,
   "netImportsTWh": 0.46,
   "ghgMt": 7.55
  },
  {
   "year": 2007,
   "demandTWh": 12.86,
   "generationTWh": 12.83,
   "renewablesShare": 0.546,
   "solarShare": 0,
   "perCapitaKWh": 1879.238,
   "netImportsTWh": 0.03,
   "ghgMt": 8.76
  },
  {
   "year": 2008,
   "demandTWh": 14.37,
   "generationTWh": 14.15,
   "renewablesShare": 0.495,
   "solarShare": 0,
   "perCapitaKWh": 2024.357,
   "netImportsTWh": 0.22,
   "ghgMt": 9.68
  },
  {
   "year": 2009,
   "demandTWh": 14.52,
   "generationTWh": 14.28,
   "renewablesShare": 0.49,
   "solarShare": 0,
   "perCapitaKWh": 1999.506,
   "netImportsTWh": 0.24,
   "ghgMt": 9.8
  },
  {
   "year": 2010,
   "demandTWh": 15.39,
   "generationTWh": 14.78,
   "renewablesShare": 0.474,
   "solarShare": 0,
   "perCapitaKWh": 2025.477,
   "netImportsTWh": 0.61,
   "ghgMt": 10.05
  },
  {
   "year": 2011,
   "demandTWh": 16.29,
   "generationTWh": 14.64,
   "renewablesShare": 0.41,
   "solarShare": 0,
   "perCapitaKWh": 1957.107,
   "netImportsTWh": 1.65,
   "ghgMt": 9.73
  },
  {
   "year": 2012,
   "demandTWh": 17.27,
   "generationTWh": 16.59,
   "renewablesShare": 0.422,
   "solarShare": 0,
   "perCapitaKWh": 2186.597,
   "netImportsTWh": 0.68,
   "ghgMt": 10.97
  },
  {
   "year": 2013,
   "demandTWh": 17.58,
   "generationTWh": 17.26,
   "renewablesShare": 0.348,
   "solarShare": 0,
   "perCapitaKWh": 2159.71,
   "netImportsTWh": 0.32,
   "ghgMt": 11.47
  },
  {
   "year": 2014,
   "demandTWh": 18.64,
   "generationTWh": 18.27,
   "renewablesShare": 0.383,
   "solarShare": 0,
   "perCapitaKWh": 2078.093,
   "netImportsTWh": 0.37,
   "ghgMt": 12.02
  },
  {
   "year": 2015,
   "demandTWh": 19.61,
   "generationTWh": 19.06,
   "renewablesShare": 1.207,
   "solarShare": 0.262,
   "perCapitaKWh": 1996.913,
   "netImportsTWh": 0.55,
   "ghgMt": 12.71
  },
  {
   "year": 2016,
   "demandTWh": 19.96,
   "generationTWh": 19.67,
   "renewablesShare": 4.372,
   "solarShare": 2.186,
   "perCapitaKWh": 1965.748,
   "netImportsTWh": 0.29,
   "ghgMt": 12.98
  },
  {
   "year": 2017,
   "demandTWh": 20.77,
   "generationTWh": 20.78,
   "renewablesShare": 6.737,
   "solarShare": 4.379,
   "perCapitaKWh": 2030.442,
   "netImportsTWh": -0.01,
   "ghgMt": 13.37
  },
  {
   "year": 2018,
   "demandTWh": 20.46,
   "generationTWh": 20.37,
   "renewablesShare": 10.604,
   "solarShare": 7.02,
   "perCapitaKWh": 1946.989,
   "netImportsTWh": 0.09,
   "ghgMt": 12.65
  },
  {
   "year": 2019,
   "demandTWh": 20.67,
   "generationTWh": 20.53,
   "renewablesShare": 14.418,
   "solarShare": 10.034,
   "perCapitaKWh": 1923.745,
   "netImportsTWh": 0.14,
   "ghgMt": 12.25
  },
  {
   "year": 2020,
   "demandTWh": 20.89,
   "generationTWh": 20.7,
   "renewablesShare": 18.937,
   "solarShare": 12.174,
   "perCapitaKWh": 1905.16,
   "netImportsTWh": 0.19,
   "ghgMt": 11.73
  },
  {
   "year": 2021,
   "demandTWh": 21.58,
   "generationTWh": 21.36,
   "renewablesShare": 22.987,
   "solarShare": 15.403,
   "perCapitaKWh": 1930.175,
   "netImportsTWh": 0.22,
   "ghgMt": 11.54
  },
  {
   "year": 2022,
   "demandTWh": 22.64,
   "generationTWh": 22.57,
   "renewablesShare": 23.128,
   "solarShare": 15.286,
   "perCapitaKWh": 2005.105,
   "netImportsTWh": 0.07,
   "ghgMt": 12.17
  },
  {
   "year": 2023,
   "demandTWh": 23.84,
   "generationTWh": 23.77,
   "renewablesShare": 21.96,
   "solarShare": 14.514,
   "perCapitaKWh": 2077.939,
   "netImportsTWh": 0.07,
   "ghgMt": 12.89
  },
  {
   "year": 2024,
   "demandTWh": 23.73,
   "generationTWh": 23.67,
   "renewablesShare": 24.081,
   "solarShare": 16.603,
   "perCapitaKWh": 2048.839,
   "netImportsTWh": 0.06,
   "ghgMt": 12.54
  }
 ]
};
